version: '3.8'

services:
    mysql-data-base:
        image: mariadb:10.6.3-focal
        container_name: mysql-data-base
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: go_api
        ports:
            - "3306:3306"
        volumes:
            - db_volume:/var/lib/mysql
        networks:
            - go-api-network

    go-api-app:
        image: go-api/app:latest
        container_name: go-api-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:8080"
        environment: 
            DB_HOST: mysql-data-base
        depends_on:
            - mysql-data-base
        networks:
            - go-api-network

networks:
    go-api-network:
        driver: bridge

volumes:
    db_volume: