version: '3.8'

services:
    mysql-data-base:
        image: mariadb:10.6.3-focal
        container_name: mysql-data-base
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            MYSQL_DATABASE: go_api
        ports:
            - "3306:3306"
        volumes:
            - db_volume:/var/lib/mysql
        networks:
            - go-api-network

    go-api-redis:
        image: redis:7.0.2
        container_name: go-api-redis
        ports:
        - "6379:6379"
        restart: always
        networks:
        - go-api-network

    go-api-rabbitmq:
        image: rabbitmq:management
        container_name: go-api-rabbitmq
        hostname: rabbitmq-host
        volumes:
        - rabbitmq_data:/var/lib/rabbitmq/mnesia
        ports:
        - "15672:15672" # management
        - "5672:5672" # amqp   
        environment:
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
            RABBITMQ_DEFAULT_VHOST: "/"
        networks:
        - go-api-network

networks:
    go-api-network:
        driver: bridge

volumes:
    db_volume:
    rabbitmq_data: